graph [
    node [ id 0 label "C" ]
    node [ id 1 label "N" ]
    node [ id 2 label "C" ]
    node [ id 3 label "N" ]
    node [ id 4 label "C" ]
    node [ id 5 label "C" ]
    node [ id 6 label "C" ]
    node [ id 7 label "O" ]
    node [ id 8 label "N" ]
    node [ id 9 label "C" ]
    node [ id 10 label "O" ]
    node [ id 11 label "N" ]
    node [ id 12 label "C" ]
    node [ id 13 label "C" ]
    edge [ source 4 target 5 label "="]
    edge [ source 11 target 12 label "-"]
    edge [ source 9 target 11 label "-"]
    edge [ source 5 target 6 label "-"]
    edge [ source 6 target 8 label "-"]
    edge [ source 8 target 13 label "-"]
    edge [ source 2 target 3 label "#"]
    edge [ source 3 target 4 label "-"]
    edge [ source 4 target 11 label "-"]
    edge [ source 0 target 1 label "#"]
    edge [ source 1 target 5 label "-"]
    edge [ source 9 target 10 label "="]
    edge [ source 8 target 9 label "-"]
    edge [ source 6 target 7 label "="]
    ]
        