graph [
    node [ id 0 label "C" ]
    node [ id 1 label "C" ]
    node [ id 2 label "C" ]
    node [ id 3 label "O" ]
    node [ id 4 label "C" ]
    node [ id 5 label "C" ]
    node [ id 6 label "C" ]
    node [ id 7 label "C" ]
    node [ id 8 label "O" ]
    node [ id 9 label "C" ]
    node [ id 10 label "C" ]
    node [ id 11 label "O" ]
    node [ id 12 label "H" ]
    node [ id 13 label "H" ]
    node [ id 14 label "H" ]
    node [ id 15 label "H" ]
    node [ id 16 label "H" ]
    node [ id 17 label "H" ]
    node [ id 18 label "H" ]
    node [ id 19 label "H" ]
    node [ id 20 label "H" ]
    node [ id 21 label "H" ]
    node [ id 22 label "H" ]
    node [ id 23 label "H" ]
    node [ id 24 label "H" ]
    node [ id 25 label "H" ]
    node [ id 26 label "H" ]
    node [ id 27 label "H" ]
    node [ id 28 label "H" ]
    node [ id 29 label "H" ]
    node [ id 30 label "H" ]
    node [ id 31 label "H" ]
    edge [ source 6 target 23 label "-"]
    edge [ source 9 target 28 label "-"]
    edge [ source 10 target 29 label "-"]
    edge [ source 3 target 18 label "-"]
    edge [ source 2 target 3 label "-"]
    edge [ source 2 target 16 label "-"]
    edge [ source 10 target 30 label "-"]
    edge [ source 4 target 19 label "-"]
    edge [ source 8 target 26 label "-"]
    edge [ source 7 target 8 label "-"]
    edge [ source 7 target 25 label "-"]
    edge [ source 9 target 10 label "-"]
    edge [ source 10 target 11 label "-"]
    edge [ source 2 target 17 label "-"]
    edge [ source 1 target 2 label "-"]
    edge [ source 6 target 7 label "-"]
    edge [ source 6 target 22 label "-"]
    edge [ source 5 target 6 label "-"]
    edge [ source 9 target 27 label "-"]
    edge [ source 5 target 9 label "-"]
    edge [ source 7 target 24 label "-"]
    edge [ source 4 target 5 label "-"]
    edge [ source 4 target 20 label "-"]
    edge [ source 0 target 4 label "-"]
    edge [ source 5 target 21 label "-"]
    edge [ source 0 target 13 label "-"]
    edge [ source 11 target 31 label "-"]
    edge [ source 0 target 1 label "-"]
    edge [ source 0 target 12 label "-"]
    edge [ source 1 target 14 label "-"]
    edge [ source 1 target 15 label "-"]
    ]
